services:
  service-utilisateur:
    build: ./service-utilisateur
    container_name: service-utilisateur
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:admin@host.docker.internal:5432/memoire_microservice_utilisateur"
    restart: on-failure
    networks:
      - app-network

  service-livraison:
    build: ./service-livraison
    container_name: service-livraison
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "postgresql://postgres:admin@host.docker.internal:5432/memoire_microservice_commentaire"
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge