

services:
  service-utilisateur:
    build: ./service-utilisateur
    ports:
      - "5000:5000"
    networks:
      - microservices-network
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  service-commentaire:
    build: ./service-livraison
    ports:
      - "5001:5001"
    networks:
      - microservices-network
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - service-utilisateur

networks:
  microservices-network:
    driver: bridge